### ISSUE TITLE
Feature Request: CLI encode with Timestamps

### ISSUE THREAD

**Issue by Gairos** [RandomEngy/VidCoder#1038]
### Feature details

Hello there !

I like this VidCoder Tool, its much cleaner than the HandBrake Version.
I want to **cut out parts of the Video** (like Intro/Outro).
Thats why i've created a Fingerprint Helper, which searchs for those Timestamps (from an example Audio File).
After that i open like "Shotcut" to get better exact Timestamps.
(Shotcut cant handle multiple audio, subtitle streams)
The thing is, there no real good solution for that right now.

Whatever.. This is just the sidestory
I know VidCoder is not a "real VideoEditing Software", but maybe its possible to just add some little Feature(s).

Probably like:
**• Multi Timstamp Selection (GUI)**
> like: 00:00:00.000-00:01:50.000,00:02:01.710-00:23:32.449

**• Add -start  and -stop offsets to the CLI**
> like: -start 00:02:01.710 -end 00:23:32.449

**• Add -d "Outputfilename" to the scan, same like for encode (CLI)**

**Comment by RandomEngy** [comment]
Splicing multiple ranges is out of scope for HandBrake/VidCoder as it's a transcoding tool only, not and editing tool.

As for the `-d` option, not sure why that would apply to scanning since the destination can be set manually after the scan.

As for the CLI, HandBrake publishes a headless CLI that supports every option under the sun. VidCoder's is much more pared down and settings are expected to be set through the encoding preset or picker. Setting start/end might be in scope as it's kind of part of the input selection. Might add that one some day when I get time.

**Comment by Gairos** [comment]
Done
https://github.com/Gairos/VidCoder

**Comment by RandomEngy** [comment]
Cool, do you want to open a pull request to bring it back to VidCoder? I would merge it to the `beta` branch as that is where new feature work is happening now.

**Comment by Gairos** [comment]
sure, if you tell me how.
First time i use Github ^^
