### ISSUE TITLE
Avg bitrate (kbps) calculated incorrectly

### ISSUE THREAD

**Issue by FCrane** [RandomEngy/VidCoder#1073]
### Problem Description

When setting e.g. "6144" as "Avg bitrate (kbps)", the resulting video has 5,9 Mb/s (6144000 b/s). It should have 6,0 Mb/s (6144 * 1024 = 6291456 b/s). 

Obviously, the "k" is incorrectly multiplied by 1000 instead of 1024.

Please fix that so that we can set correct values in Mb/s, etc.

Thanks!

### What version of VidCoder are you running?

8.9 Beta Portable

**Comment by FCrane** [comment]
I just noticed that MediaInfo also interprets 6144000 b/s as 6144 kb/s - is this on purpose? Should this not be handled the same way all computer "k"s are used (1024 instead of 1000)?

**Comment by RandomEngy** [comment]
It's just the convention of how video bitrates specified. There are some that try to use the term "kibibyte" or KiB to refer to 1024 bytes, to distinguish it from the scientific prefix kilo which means 1000. It's not in wide use so some OSes like Windows don't use that notation (and it sounds weird to me), but I can see its merit.

The other quirk is that it specifies bits instead of bytes, though that's a bit easier to pick out because it uses the lowercase `b` in `kbps`.

Not sure how the convention came about, but it's not really any more "wrong" than the convention for how OSes display file sizes.

**Comment by RandomEngy** [comment]
Yes, that's right. VidCoder tries to stay consistent with how the units are commonly used in that context.
