### ISSUE TITLE
Metadata Pass-through Does Not Copy Comment Field

### ISSUE THREAD

**Issue by jlikens** [RandomEngy/VidCoder#1193]
### Feature details

One of the core metadata fields in MKV and MP4 containers is the Comments field. Some software uses this field to store structural or informational metadata, such as normalization information, original source material, etc. 

Since the data in this field is not passed through to the output file, this data is lost. One possible workaround would be to send the source and destination files to a post-processing script to do the copying, but VidCoder does not seem to allow sending the full path to the these files to the post-encoding script.

So, there are (at least) two possible ways to address the above:

1. Add the Comment field to the list of metadata that is copied from the source to the destination
1. The post-encoding arguments should allow for a new replacement tags, such as "{fullsourcepath}" and "{fulldestinationpath}"
   1. While not a direct implementation of the Comment passthrough, it would allow power users a more robust set of parameters for post-processing scripts, including writing something that could do the Comment copying

**Comment by RandomEngy** [comment]
Do you have Pass through Video Metadata checked in the Picker window?

In any event, I do see that `{fullsourcepath}` and `{fulldestinationpath}` would be useful on the post-encoding script, I'll add those when I get some time.

**Comment by RandomEngy** [comment]
For StaticResolver test, you can call `StaticResolver.SetResolver()` with a custom IResolver that returns whatever you want. But if you'd like to go crazy and switch everything to constructor DI, that's fine with me too. I haven't been the most rigorous with the DI setup since I'm the only one that develops on it most of the time and I don't have a ton of unit tests.

Anyway, happy to look at whatever PR you've got there.

**Comment by RandomEngy** [comment]
I added a `{sourcepath}` token to the post-encoding options in 10.9 Beta. The `{file}` token already is the full destination path.
