### ISSUE TITLE
Listed Output Resolution seems weird

### ISSUE THREAD

**Issue by pizzaboyuk** [RandomEngy/VidCoder#277]
![2017-11-25_22-30-48](https://user-images.githubusercontent.com/29855772/33231486-10969e8c-d231-11e7-93b2-e562bd53b98d.png)
The source file I'm using is a DVD ISO and the image is more square (left & right borders, so I presume 4:3) than rectangular. Haven't encoded this yet, just wondering why the output height would be bigger than the listed Storage and Display Heights. Is the Downscale Only setting not working or are my expectations on how this should work incorrect?

Also, why is the display resolution different from the storage resolution?

Thanks.

P.S. Just noticed for this file, when I dragged and dropped the ISO into VidCoder, it automatically has a selected Time Range of 0:00:00-0:00:00, though the bar does show a blue selection range?!?!
![2017-11-25_22-47-24](https://user-images.githubusercontent.com/29855772/33231612-129fa924-d233-11e7-9fd9-5250f2d4463f.png). 

Haven't had this happen before, usually VidCoder has correctly determined the correct length of the DVD...

**Comment by RandomEngy** [comment]
I think this is just an inconsistency with how VidCoder calculates the display resolution from the source resolution and PAR. There isn't really a "correct" answer to that question. For purposes of the DVD scenario, you usually think about it squeezing in or stretching out to fit the actual resolution of the display (which back in the day always 480 pixels high). When I auto-calculate the output resolution in this case I am trying to minimize data loss, so I stretch out the vertical pixels instead of squishing in the horizontal pixels. That means a better looking picture for HD displays (which is nearly everything these days).

**Comment by RandomEngy** [comment]
About the 0:00:00, that looks like an issue with the source. Also VidCoder doesn't handle the corner case perfectly, it looks like.

**Comment by Mister-XY** [comment]
Hello i want to reopen this error  because i have see this resolution error also.
with handbrake, i have the correct resolution and with vid coder, i have the wrong.

**Comment by Mister-XY** [comment]
Here are the settings in Vidcoder
![vidcoder](https://user-images.githubusercontent.com/10309056/45859700-9f7d4880-bd63-11e8-815d-4d070af79368.png)

And the same via handbrake
![handbrake](https://user-images.githubusercontent.com/10309056/45859708-a99f4700-bd63-11e8-9701-13133d77c025.png)

In this case, i must change it manualy for the correct resolution. Handbrake do it automatically.

**Comment by RandomEngy** [comment]
You need to check the "Anamorphic" checkbox in VidCoder.
