### ISSUE TITLE
VidCoder 3.4

### ISSUE THREAD

**Issue by JonnyThree** [RandomEngy/VidCoder#294]
This new version is full of bugs. Simply create a custom profile, load a movie, edit the profile (example: resizing), start encoding and click on encoding settings button.
I'm forced to downgrade to v3.3 because after the Exception appear, every restart without doing nothing, it will always popup and the software become unusable.
I think that no-one needs those encoding profiles changes, old system was working good, without any bugs and also editable (removing entries) by modifying the file builtinpresets

**Comment by RandomEngy** [comment]
Should be fixed in 3.5 Beta. If you don't like running into bugs, I suggest using the Stable version. If you don't like the built-in presets, save the subset you want to keep as custom presets, then collapse the built-in node. Supporting the edit of the built-in presets is not something I'm interested in since it makes updating those built-in presets more complicated and difficult, and it's already possible to make copies of them an change them as custom presets.

In any event, getting the exception stack trace is helpful for me to squash bugs.

**Comment by JonnyThree** [comment]
bugs are normal, regressions are not, especially in this case when profile managing changes are really not needed. so i say goodbye to vidcoder and i switch to original handbrake,.

**Comment by RandomEngy** [comment]
That's a lot of entitlement for the beta version of freely provided software with issues fixed within 24 hours of them being reported.

Have fun with HandBrake. Make sure to use the nightlies so you have more opportunities to complain to them every time something breaks.

**Comment by JonnyThree** [comment]
yes i'm using nightly version, and i have already removed all the useless preset voices in the json file.
