### ISSUE TITLE
Audio question:  448 bitrate vs 640

### ISSUE THREAD

**Issue by Charvelx04** [RandomEngy/VidCoder#306]
I am curious about the difference in the audio bitrate, when looking at the comparison from the audio bitrate properties of an uncompressed DVD .vob file at 448kbps, and it's encoded .mp4 counterpart at 640kbps.

When I encode an mp4 from a DVD, I use the following settings in the Audio tab.

Audio settings used:
Codec: AC3
Bitrate: Auto
Target Stream: Stream 1
Mixdown: 5.1 Channels
Gain: 0
DRC: 0
Sample Rate: Same as Source
Passthrough if possible: Not checked

It seems that the Auto setting for the bitrate, sets the audio to 640, so my questions are:
Is there any true difference between 448 and 640?
If VidCoder uses Handbrake for it's encoding engine, and HB would set this as 448, why does VC set it to 640?
Where does the additional 192kbps come from?

Just curious!  :)    Even though I have both programs, this one I favor best.

Thanks for the time in reading this!!

**Comment by RandomEngy** [comment]
VidCoder first determines what the encoder, channel layout and sample rate will be for the output, then plugs that into a method in HB core that gives the recommended default bitrate.
It looks like HandBrake windows UI just sets the output bitrate to the same as the input bitrate. Which doesn't make as much sense to me, for a few couple reasons:
1) When you are trying to preserve quality, you want to avoid further degradation. If the source has a low bitrate and you re-encode with a low bitrate it's going to sound even worse.
2) The source and target codecs might have different efficiencies, meaning you could get a track that's too large or a track that sounds bad.
3) You want to take the channel layout and sample rate into account because those both determine how much data you need to represent the audio clearly.

**Comment by Charvelx04** [comment]
Appreciate the info!
Yeah... I've only seen HB's UI settings with a max of 448kbps for AC3 audio, however I haven't seen any VOB files in excess of 448 with 5.1 surround.

I'm going to make some tweaks within the custom settings I've been creating for VC using the information you gave me.  It's one thing to live with some visual compression quality given the nature of the mp4 format, but I like having all my movies with the best sound quality.

Thanks again!
