### ISSUE TITLE
add "AFS" to encode details window

### ISSUE THREAD

**Issue by Fraghera** [RandomEngy/VidCoder#33]
add average-estimated file size info to encode details window plz

also u can merge encode details windows to main program window too

separate windows looks bad

**Comment by RandomEngy** [comment]
Not sure how I would estimate the final file size, since different parts of the movie could take up different amounts of space when using quality targeting. For using bitrate it could be tricky because the measured file size lags behind the actual encode progress. You can also see an estimate of the final size on the Video tab of the encoding settings window.

About the separate window, it will probably stay like that. There's no room to put all of that in the main window. Maybe if I ever get around to doing a docking system that would help.

**Comment by Fraghera** [comment]
it is for info only so it doesnt have be %100 right. just use the old fashion method.
yes maybe there is no room for now but if user wanna see detailed windows, program just can expand itself. u should consider having a layout like ccleaner. 
just keep it simple.
your gui is really good and will be very popular soon.

**Comment by RandomEngy** [comment]
Thanks! I think it has been getting gradually more popular for a few years now.

Though the problem with expanding your window is that you can quickly run out of space on a monitor for the window. Ideally it would be in a docking system so you could attach it to your main window on whatever side you wanted, or float it somewhere. But I just haven't had time to work on that.

As for the file size estimate, I think it would be too much guesswork for not enough payoff. If you're using constant quality you probably don't care too much exactly how big the file is going to be. If you're using bitrate you see the estimated size in the Video tab. If you're using target size you have the number right there.

**Comment by Fraghera** [comment]
fair enough
