### ISSUE TITLE
Subtitles size

### ISSUE THREAD

**Issue by Mister-XY** [RandomEngy/VidCoder#387]
Hello, I have a little question or an improvement request.
Is it possible that in the Untertiel menu beside: "Name, standard, only Forced, burn-in" and the current size is there? So you can immediately see how big the subtitles are and you know directly whether they are "Normal" subtitles or "forced"
And is that possible to show in audio tracks the bitrate from the audio track?

**Comment by RandomEngy** [comment]
Showing the existing subtitles size isn't possible because the HandBrake API I use doesn't expose that. You would need to ask them to add that capability. If subtitles are burnt in the source file, they won't show up on the subtitle list, so all source subtitles are going to be "soft" or non-burnt in.

As for showing bitrate and sample rate, I could add that to the list.

**Comment by RandomEngy** [comment]
Added bitrate and sample rate to audio list in 4.12 Beta.

**Comment by Mister-XY** [comment]
Cool, i will tested it
