### ISSUE TITLE
Why is not version 3.16 updated?

### ISSUE THREAD

**Issue by lucabis** [RandomEngy/VidCoder#461]
Hello, since the version 4 is still unstable because version 3 is not updated with the new core of handbrake? Thank you

**Comment by RandomEngy** [comment]
Because:

1) Some changes to the GUI are required are required to use the new HandBrake core correctly
2) Those changes are in the Beta branch and wrapped up with all the other Beta features
3) I want to have the stable core sit for a couple weeks in Beta to work out any bugs that might pop up
4) I want to wait for translations of the new features to come in before releasing to Stable
