### ISSUE TITLE
all new beta .exe installation problems

### ISSUE THREAD

**Issue by contrariwise1** [RandomEngy/VidCoder#464]
As title suggests, having issues installing any of the new beta's. I install it and it says i need to run a certain version of vidcoder, like newest versions says must run 3.15 to finish install. I start 3.16 still can't use beta, uninstall to 3.15 like it says to do and it still won't run. If beta's can be run and installed seperately from official releases why is it asking to run the official release?

**Comment by RandomEngy** [comment]
It it saying "your data is too old to upgrade"? I think the issue is that you have an old VidCoder.sqlite file in %appdata%\VidCoder-Beta . You need an older version to upgrade the file, but it's looking in its own folder and not the beta folder for the file to upgrade.

You can delete this file and start fresh. Or if you want to upgrade it to keep your presets and preferences, you should be able to follow these steps:

1) Copy VidCoder.sqlite from %appdata%\VidCoder-Beta to %appdata%\VidCoder
2) Run 3.15 Stable to upgrade it
3) Copy VidCoder.sqlite back from %appdata%\VidCoder to %appdata%\VidCoder-Beta
4) Run 4.x Beta

**Comment by contrariwise1** [comment]
Thanks, it now works. Some features from handbrake that i can't find in your version, 2 pass encoding and turbo first pass. And for subtitles, I would like to see foreign audio scan, forced, and burned in defaulted like there version, most of the time i forget to add them. Attached screenshots.
![screenshot 3](https://user-images.githubusercontent.com/46210577/50519597-ba113d00-0a89-11e9-8ab2-1d81f09b8287.png)
![screenshot 2](https://user-images.githubusercontent.com/46210577/50519650-ea58db80-0a89-11e9-82e6-8523787a6e4e.png)
