### ISSUE TITLE
More Keyboard Hot-keys?

### ISSUE THREAD

**Issue by hl2guide** [RandomEngy/VidCoder#493]
Please consider adding more keyboard hot-keys for common actions within VidCoder.

Maybe for the toolbar it could be something like..
Global options: Ctrl+G
Encode: F9
Import Preset: Ctrl + <
Export Preset: Ctrl + >

**Comment by RandomEngy** [comment]
Made a few changes in 5.6 Beta:
* Changed the Global options hotkey from "F4" to "Ctrl+G"
* Added key tips to the ribbon when you press "Alt".
* Added "F5" hotkey for starting/resuming encodes.
* Fixed issue where hotkeys wouldn't work after opening Global Options from a ribbon click and closing it again.

I didn't add hotkeys for Import/export preset because I think those aren't as often used and would work better with "chord" hotkeys, which I have not set up support for yet. (Ctrl+I+P, Ctrl+I+Q, Ctrl+E+P, Ctrl+E+Q).
