### ISSUE TITLE
Framework 4.7.2

### ISSUE THREAD

**Issue by smanross** [RandomEngy/VidCoder#505]
Is there any chance that you don't specifically need the .NET Framework 4.7.2 and could work with .Net Framework 4.6?  VidCoder 4.32 seems to want/need this newer framework where version 3.16 is okay with 4.6.

I am using W10 Build 1511 and the highest framework I can use is 4.6.  Obviously my option is to upgrade builds of W10, but I actually love 1511 and think the OS has gone downhill since 1511.

If its not possible I understand.  I know what I have to do to get the newer version to work (upgrade W10 builds).

Please and thank you.

**Comment by smanross** [comment]
p.s. I love this product!

**Comment by RandomEngy** [comment]
Have you tried installing the standalone .NET 4.7.2 installer?

Also the reason I upgraded was because the HandBrake team upgraded the interop DLL to target 4.7.1, so that required me to upgrade. That's not 100% an impossible problem as the interop code could be forked or possibly changed to target a lower framework.

But there is another transition on the horizon: a move to .NET Core 3.0. I'm not sure yet what it means for people like you who don't upgrade their OS, but I hear one of the advantages is that it can install side by side with other versions.

**Comment by RandomEngy** [comment]
Ahh looks like it is indeed not supported on the old build: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies . Anyway I would hold on for the .NET Core 3.0 version. Or just let Windows do its upgrade. :)

**Comment by smanross** [comment]
Thank you for the information.

And Again, THANK YOU FOR ALL YOU DO FOR THIS PROJECT!

Steven
