### ISSUE TITLE
"media creation date" is wrong

### ISSUE THREAD

**Issue by gordielachance** [RandomEngy/VidCoder#562]
Hi, after I've read [this topic](https://github.com/HandBrake/HandBrake/issues/51), I decided to use VidCoder and checked the option **Advanced -> Preserve Created and Modified time when converting files** to keep my original video data dates.

It seems to work, but does not sets the right info for "media created" field.  
File created / modified are ok. (i'm on Windows here)
But when uploading them to Google Photos, it seems that it relies on "media created", thus sorts wrong...

Thanks !

**Comment by RandomEngy** [comment]
That makes a lot of sense. The only complication is that those fields are part of the file contents itself. Traditionally I have been leaving 100% of the file in the control of the HandBrake library, so I would normally say this should be a HandBrake feature.

But in this case they don't seem to think that metadata should be preserved, which I don't agree with. Also I think it would be possible to check the metadata before config and alter it after, since that is much more straightforward than messing with the picture or audio encoding.

I'll put it on the backlog, though no guarantees I'll get to it soon.

**Comment by queroin** [comment]
Any update on this? I'm struggling with converting .avi, .mov videos to mp4 to be uploaded on google photos and so far this is the closest GUI converter I found that does its job. 👍

**Comment by RandomEngy** [comment]
In 6.9 Beta, the "Preserve Created and Modified time when converting files" will also preserve the "Media Created" property.

**Comment by openfred65** [comment]
I confirm that beta version (6.31 when I am writing these words) is _really_ keeping the creation date.

Please notice that there are 2 creation date : **Media creation date** eg. 01/01/2009 16:31 and **File creation date** (when you actually wrote the file on the current storage media) eg. 10/12/2020 22:23.
On windows **File Properties** and then **Detail tab** to check.

How to put this version 6.31 on the stable branch ? 
I was about to scrap VidCoder as I thought it wasn't keepting media creation date (5.21), whereas version 6.31 is currently doing the job pretty well.

**Comment by RandomEngy** [comment]
When HandBrake releases a stable version, VidCoder will do so as well.

**Comment by MudassarAli** [comment]
I can also confirm that Beta 6.35 preserves Media Created Date (Which i believe every converter should do). Thanks a lot for this feature.
