### ISSUE TITLE
Advanced Tab Being removed

### ISSUE THREAD

**Issue by snintendog** [RandomEngy/VidCoder#604]
Once again a good feature being removed because its "inaccurate", Lazy stuff like that is BS and why i left handbrake in the dust and came over to vidcoder. NO ONE WANTS TO BE A PROGRAMING GOD to enable a freaking option. Reverting to back to 4.

**Comment by snintendog** [comment]
Adding that it wiped the setting used Prior to the advanced tab removal all my settings have been reduced to only REF=5:bframes=5 defualt

**Comment by snintendog** [comment]
After reverting to 4.36 only the encoder setting opened by 5 were reset. Thankfully i keep backups of all these settings. Secondary note The UI to selec encoder settings is fully broken and can only be selected via the picker or creating a new one in while editing and existing encoder setting.

**Comment by RandomEngy** [comment]
* Automatic backups are kept in %appdata%\VidCoder\Backups .
* If you have an encoding preset selected in the picker, it prevents you from changing it any other place. When you could change them both independently, there was a lot of confusion about which was actually active.
* For the advanced options, [refer to the docs](https://en.wikibooks.org/wiki/MeGUI/x264_Settings) and use setting1=value1:setting2=value2 . You don't need to be a programming god to do that.

**Comment by snintendog** [comment]
Nothing has been addressed Once agin YOU CANT EVEN OPEN ANOTHER PRESET DUE to your bad design TO EDIT THEM WITHOUT ASSIGNING IT TO A PICKER BEFORE HAND.

second the fact that it deleted any setting in a PRIOR encoder is in excusable.

Third "level=4.1:vbv-bufsize=78125:vbv-maxrate=62500:rc-lookahead=60:ref=8:bframes=16:b-adapt=2:subme=10:analyse=all:trellis=2:aq-strength=0.6:psy-rd=0.4,0.00:deblock=1,1" tell me that this makes sense to someone using a program instead of a UI Which was already in place just to be removed. Utter rubbish Laziness.

All for what some WebM crap and the ability to keep failed encodes for some ungodly reason?

**Comment by RandomEngy** [comment]
About your preset issues, I really don't understand what is going wrong. Could you post a separate issue with clear steps to reproduce and what the expected behavior is?

Also, about losing your settings: I cannot reproduce that. I wrote logic to keep whatever you had before in the More Settings box. I just ran another test upgrade now and it saved the string exactly as it was.

And if you're having a hard time with typing in the options, I would suggest you stop trying to tweak individual x264 settings and instead use the preset slider and available tunes. They were written by very knowledgeable people and they give very good speed/compression efficiency tradeoffs. It is likely that if you pick the right preset, your encode times or picture quality will improve.

As for your "laziness" comment: I write software to help people solve problems. The "advanced" tab is not helping in that regard. It draws away attention from the settings that matter and you get worse outcomes. Why should I spend any amount of time maintaining something that has a negative impact on the user's videos? Why should I ask the volunteer translators to translate a bunch of long-winded explanations into 22 languages? Why should I sacrifice other features, or time with my family to make it marginally easier for people unsuccessfully improve on the x264 developer's presets?

As for the option to keep failed encodes? I implemented that because someone had a reasonable use case for doing so and it helped them solve a problem. And they _asked nicely_ .
