### ISSUE TITLE
difference between constant quality and average transfer rate

### ISSUE THREAD

**Issue by lucabis** [RandomEngy/VidCoder#695]
Hi, I wanted a clarification between the two items in question: I performed an encoding of the same film with a constant speed of 18 and then with an average transfer speed of 7500 kbps in 2 steps. The file size was almost identical and the visual quality also looks the same.
So why use 2 settings that give the same result?
Thank you.
Luca

**Comment by RandomEngy** [comment]
The only reason to use bitrate/2-pass would be if you were really concerned about staying under a specific size limit. But I recommend Constant Quality for all cases because as you mentioned, you get just as good or better results while spending less time encoding. That's why all of the built-in presets use Constant Quality.

https://vidcoder.net/Documentation/VideoQualityOptions.html
