### ISSUE TITLE
Bugfix:  Auto Adjustment for the SIZING not working.

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#744]
Hello,

  Sorry if I am a bit lazy, but when you do lots of encoding, all the small tweaks to acheive faster and without errors is the best.

So... under the SIZING TAB, when you ENTER a Max Width: 720 by example, the MAX HEIGHT is suppose to change **automatically** but it doesn't.  This is what HANDBRAKES do.

![image](https://user-images.githubusercontent.com/4656308/106619428-965d3280-653e-11eb-8c86-4be0dc884989.png)

As you might notice, you can see in the snapshot above, the MAX HEIGHT is not the same as the OUTPUT information.

Keep it up,

**Comment by quebecman** [comment]
Handbrake have a neet option: Keep Aspect Ratio... Well... sincerly, the checkmark doesn't have to be there... but when changing manually, would be nice to change the other number.

![2021-02-02 13_41_46-HandBrake](https://user-images.githubusercontent.com/4656308/106647177-9835ee80-655c-11eb-85a2-8803815764ab.png)

**Comment by RandomEngy** [comment]
The max width and max height are both optional constraints. VidCoder will always try to maintain the aspect ratio in Automatic mode, even when you haven't specified a width or height constraint. You need to use Manual sizing mode to change the aspect ratio.

HandBrake changes the width/height values automatically based on the source aspect ratio, but VidCoder is more batch-focused so it always shows you the same constraints no matter what the source is. VidCoder also allows you to edit the encoding settings without any source loaded, because the assumption is that the settings will handle any source you throw at it.

I have considered adding some helpers to suggest a width or height based on some preset aspect ratios, but haven't figured out an easy way to do it.

Are you setting up the max width/height a lot? I thought in normal workflows people would set up a preset once and re-use it many times.

**Comment by quebecman** [comment]
Hmmmm... Well... Yes, always but I do understand that I am not part of the majority.  I have to encode SD, 720p, 1080... when I send to my client.

Hmmmm... by curiosity, if I have a 1080 (1920x1080) source and I want to downgrade it to SD, what would happen if I pick AUTOMATIC?   What would be the final result for the sizing?  I can go ahead and give a try.

Finally, I think that it would be good to have an option in the PICKER if possible.

**Comment by RandomEngy** [comment]
If you have a 1920x1080 source and pick automatic, and leave the max width and max height blank, it will encoded as 1920x1080. If you specified 720 as max height and left max width blank, it would be encoded as 1280x720.

The picker specifies what you're encoding and where it goes, but not how, so I wouldn't put sizing options on the picker. You can choose to automatically use a specific encoding preset on a picker though.

**Comment by quebecman** [comment]
Yes, this what I do... I do ENCODING PRESET.

Thanx. Regards.

________________________________

**Comment by quebecman** [comment]
Well.. this is driving me insane.  When creating few movies... I always have to go in HANDBRAKE to make shure the SIZING is correct.  I do not know if there is something easily that could be done.

**Comment by quebecman** [comment]
I think I have figured something out that I didn't noticed.  If I enter down only the MAX (720) and leave the HEIGHT empty with AUTOMATIC, I think it should do the trick.

**Comment by quebecman** [comment]
You can go ahead and close this thread.  It wasn't a bug but more of a behavior on how handbrake acts.

Thanx.
Regards.
