### ISSUE TITLE
Encoder preset issue in BETA version.

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#756]
This is weird but it seems that ENCODE PRESETS are FROZEN.  When you try to reach them with the mouse, we are unable to do it.

 -- Unable to pick and or edit any encoding profile;
 -- Unable to delete any encoding profile...

  Note that in version 5.1, this problem doesn't occur.

**Comment by RandomEngy** [comment]
Do you have a preset selected in your Picker window?

**Comment by quebecman** [comment]
I have completely uninstalled everything and re-installed it.  Now it works.  Weird since this is version 6.2.0.

  -- Would be nice to be able to EXPORT ALL CONFIG, including the PICKER.

After re-installing, I was able to re-import the ENCODING settings but not the PICKER.

**Comment by RandomEngy** [comment]
You can back up %appdata%\VidCoder-Beta\VidCoder.sqlite and it will restore everything.

**Comment by quebecman** [comment]
Again, it did the same thing, my ENCODING SETTINGS are FREEZED UP and there is no way to pick one up.

**Comment by RandomEngy** [comment]
It's intentional. People were getting confused when they had a picker set up to choose encoding preset A but then switched to edit preset B and didn't see any of their changes take effect. So when you've picked an encoding preset in the picker, you can't switch. I've changed 6.24 Beta to give a more helpful message when you try to change presets, rather than just stopping you.
