### ISSUE TITLE
Is there anyway that VIDCODER can pick only FORCED SUBTITLES in Picker?

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#761]
Would be nice if possible to put the LANGUAGE + PICK ONLY FORCED SUBTITLES.

  -- When you look in MEDIAINFO, when we take a look at the COUNT OF ELEMENTS, it gives out 19.  This meens there are only 19 caracters in the FORCED items.  If it would be FULL subtitles, you would have around 1000.

Text
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 17 min
Bit rate                                 : 0 b/s
**Count of elements                        : 19**
Stream size                              : 435 Bytes (0%)
Title                                    : Forced
Language                                 : French
Default                                  : Yes
Forced                                   : Yes

**Comment by RandomEngy** [comment]
There is a "Forced only" checkbox in the Picker that will pick only forced subtitles. It's usable with the "Language" mode.

**Comment by quebecman** [comment]
It does not Work i havé tried it already

Envoyé de mon iPhone

Le 16 févr. 2021 à 23:06, David Rickard <notifications@github.com<mailto:notifications@github.com>> a écrit :


There is a "Forced only" checkbox in the Picker that will pick only forced subtitles. It's usable with the "Language" mode.

**Comment by quebecman** [comment]
![image](https://user-images.githubusercontent.com/4656308/108156047-feb72280-70ad-11eb-98f7-ee0766f6b21b.png)

**Comment by quebecman** [comment]
Is this a hit or miss option in HANBRAKE or it will select by DEFAULT the smallest UTF file?

**Comment by RandomEngy** [comment]
That subtitle track does not support the "forced" flag on subtitles. So you cannot apply the "forced only" flag to it.

**Comment by quebecman** [comment]
I don't understand this FORCE stuff.  In fact, I have never seen handbrake in years the FORCED ONLY box not grayed out.  But I can asshure this SUBTITLE is the forced one.

**Comment by RandomEngy** [comment]
Some subtitle tracks support certain lines being marked as "forced". That means you can choose to see all the lines, or you can choose to just see the "forced" lines. For example you might have an English subtitle track, where only the lines that describe non-English dialogue are marked as forced. If you can't hear the audio, you'd pick the whole track, otherwise you'd want to pick "forced only" and get just the bits that cover the foreign dialogue.

If the "forced only" box is grayed out in the main window, the subtitle format does not support this flag, so you can take the whole thing or leave it. In this case it doesn't matter if you've chosen "forced only" in the picker as it can't have any effect.

**Comment by quebecman** [comment]
Was just curious about the FOREIGN Subtitle.  Should this be ADDED in the PICKER under the LANGUAGE TO ADD?

 I am a bit confused about this FOREIGN.  

In other words, does handbrake DETECTS FOREIGN language by default?  If so, can this be addup in the PICKER under the language?

**Comment by RandomEngy** [comment]
Foreign audio search is a special mode where it tries to find a subtitle track that has few lines in it, that looks like it's a track for a foreign language. That search code is built into HandBrake. The Language-based selection is done with VidCoder, as it looks over the list of subtitle tracks. It doesn't look inside any of these tracks the way Foreign Audio Search does.

**Comment by quebecman** [comment]
Hmmmm, as a good practise, should FOREIGN LANGUAGE always be ADD UP with other langage?

**Comment by RandomEngy** [comment]
Took a closer look at this. Apparently, a lot of people like to use Foreign Audio Search with Forced Only and Burn-in flags enabled. https://www.reddit.com/r/handbrake/comments/ajxnwv/foreign_audio_subtitles_how_the_hell_does_this/ . I'll put something on the backlog to make it an optional addition to the index/language based picking rather than either-or.

**Comment by quebecman** [comment]
Nice!  You put me in doubt.  I was just reading on handbrake website and apprently, handbrake tries to detect the foreign langage.  Well, I don't mind putting it all the time to make shure it's there.

I don't think this will take that much space in the file.

Thanx. Regards.
________________________________

**Comment by quebecman** [comment]
I was encoding GAME OF THRONES.... and they have lots of foreign langage.

Thanx.
Regards.
________________________________

**Comment by RandomEngy** [comment]
Added ability to set Foreign Audio Scan separately from the main selection method in v6.25 Beta:

![image](https://user-images.githubusercontent.com/9450861/108731471-71c2fd80-74e1-11eb-9827-09e06886ac8e.png)

**Comment by quebecman** [comment]
Nice.  Thanx.
________________________________
