### ISSUE TITLE
Can the avg bitrate of the video encoding in the encoding preset  automatically copy the original avg bitrate of the video?

### ISSUE THREAD

**Issue by h45251880** [RandomEngy/VidCoder#767]
Can the avg bitrate of the video encoding in the encoding preset  automatically copy the original avg bitrate of the video?
Hope that the avg bitrate of the encode video can copy the source video in the future or Is there any way to copy avg bitrate to encode video? I see that the avg bitrate does not have this option.

**Comment by RandomEngy** [comment]
No, I don't think that will ever be available. Quality targeting is better at preserving the source video. Also different encoders have different efficiences and would require different bitrates to produce the same picture quality. And if you were encoding a video with a low bitrate it would look even worse, because re-encoding always degrades quality.

I would encourage you to use quality targeting to better automatically preserve the picture quality.

**Comment by h45251880** [comment]
ok~
