### ISSUE TITLE
Bug report: Cannot switch encoding preset stuck even if OK button pressed multiple times

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#777]
I have pressed accidentally on the ENCODING SETTING button and I got the following message below, wich is normal and ok when using PICKER. 

![image](https://user-images.githubusercontent.com/4656308/110259926-0e70ab00-7f78-11eb-8c6f-148585f92396.png)

 The bad behavior is I have pressed the OK button zillions of time and I am stuck there.  There is no way to get out.  It keeps poping up.

 May be a good solution would be just to GRAY OUT the encoding settings and an over TOOLTIP displaying something like if you want to change this, put back to default picker.

Can't say if this was prior to version 6.26.

Thanx.
Regards.

**Comment by RandomEngy** [comment]
I am going to keep this message since historically there have been a lot of people who do not understand why they cannot switch presets after locking it in the Picker. But I will fix the issue with it opening repeatedly if you can give me some more specifics on how to make the issue occur.

Does this happen reliably after you do something specific? If so, could you share the steps you used to make it happen, and your VidCoder.sqlite file from Help -> Open App Data folder?

**Comment by quebecman** [comment]
This is weird but it's actually fixed in version 6.27.  Note that I was able to reproduce easily this problem.

**Comment by RandomEngy** [comment]
Let me know if you get repro steps on 6.27 or later.
