### ISSUE TITLE
Is there anyway to get an average of the output filesize when using CONSTANT QUALITY?

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#799]
Like already said before, I have always used handbrake since the age of stone and I always asked myself the following:

 I do understand handbrake and all the other software on the planet doesn't do that but is there anyway when VIDCODER scan the file to get and approximate file size at the end when using constant quality?

  The thing is handbrake is able to calculate the ETA of a batch queue but not the constant quality...  this is weird.

Thanx. Regards

**Comment by RandomEngy** [comment]
It calculates the ETA based on encode speed and current progress. But we don't actually have a up-to-date picture of the file size. The encoding is done to an in-memory buffer and periodically flushed to disk. There's a lag of unknown size, that depends on the encoder internal implementation. That means it will always be incorrect.

There's also changes in picture complexity. For example, credits at the end take a lot less data to encode since they are slow-moving and simple.

**Comment by quebecman** [comment]
Answered.
