### ISSUE TITLE
No offline installer

### ISSUE THREAD

**Issue by bonerfart** [RandomEngy/VidCoder#82]
Installers demanding unfiltered net access is IMHO a misdemeanor, and the widespread blind acceptance nowadays is one of the major causes virii and trojan have free reins if most of userland. I may be paranoid, but the fact remains 1.5 can be installed on non-networked machines, 2.x can't. Just a nudge to reconsider.

**Comment by RandomEngy** [comment]
In the 2.x Beta I upgraded to use NET Framework 4.6. I added a feature where it will download the bootstrapper and install it for you inline if you don't have it. I'm guessing that you don't have .NET Framework 4.6, because it installs just fine without internet access if you have it already.

I could make the error message a bit better when the bootstrapper download fails, but I'm keeping the feature.

**Comment by RandomEngy** [comment]
I've improved the error message when it fails to download the bootstrapper. It now tells you that it's trying to download .NET Framework 4.6.
