### ISSUE TITLE
New Video Filters Missing Tooltips

### ISSUE THREAD

**Issue by LeeThompson** [RandomEngy/VidCoder#908]
This is a minor issue but the new video filter options are missing tooltips.

**To Reproduce**
Under a preset's video filters hover over any of the following combo boxes.
1. Chroma smooth
2. Colorspace

**Expected behavior**
There should be nice tooltips like for the other options.

(v6.4.1)

**Comment by RandomEngy** [comment]
I've just been copying the ones they have on HandBrake, but HandBrake doesn't have any text for those filters. If you want to do some research and put something together I could add them in as tooltips.

**Comment by LeeThompson** [comment]
(from https://handbrake.fr/docs/en/latest/technical/filters-summary.html)

**Chroma Smooth**

Reduces chroma noise, rainbows, and other prominent visual artifacts. Useful for resolving various color-related issues, especially with lower resolution content from analog sources, e.g. poor quality DVD and VHS sources. The blurring/smoothing algorithm is the same as used by the unsharp filter.

**Colorspace**

Colorspace + tonemap filter. Can change/tonemap the colorspace of the video into one of the following:

BT.2020
BT.709
BT.601 SMPTE-C
BT.601 EBU
If this set to “Off” then HandBrake will keep the colorspace of the video.

**Comment by RandomEngy** [comment]
I added the Chroma Smooth tooltip to v7.0 Beta. I didn't add the colorspace tooltip because right now I am dynamically loading in the available options from HandBrake and I don't want to have to do manual updates when these change. Also the extended description doesn't really add much extra explanation beyond what the label already tells you.
